itysk/urls.py
from django.conf.urls import url, include
from django.contrib import admin as tysk_admin

urlpatterns = [
    url(r'^tysk/admin/', tysk_admin.site.urls),
    # https://stackoverflow.com/questions/48608894/specifying-a-namespace-in-include-without-providing-an-app-name
    # url(r'^tysk/', include('tysk.urls', namespace="tysk")),
    url(r'^tysk/', include(('tysk.urls', 'tysk'), namespace="tysk")),
    url(r'^tysk/accounts/', include('allauth.urls')),
]

tysk/urls.py
from django.conf.urls import url
from tysk import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^doctors/$', views.DoctorsList.as_view(), name='doctors-list'),
    url(r'^doctors/(?P<pk>[0-9]+)/$', views.DoctorDetail.as_view(), name='doctor-detail'),
    url(r'^doctors/add/$', views.doctor_add, name='doctor-add'),
    url(r'^doctors/(?P<pk>[0-9]+)/update/$', views.DoctorUpdate.as_view(), name='doctor-update'),
    url(r'^doctors/(?P<pk>[0-9]+)/confirm/$', views.DoctorDelete.as_view(), name='doctor-delete'),
    url(r'^mains/$', views.MainsList.as_view(), name='mains-list'),
    url(r'^mainsget/$', views.main_filter, name='main-filter'),
    url(r'^mains/(?P<pk>[0-9]+)/$', views.MainDetail.as_view(), name='main-detail'),
    url(r'^mains/add/$', views.MainCreate.as_view(), name='main-add'),
    url(r'^mains/(?P<pk>[0-9]+)/update/$', views.MainUpdate.as_view(), name='main-update'),
    url(r'^mains/(?P<pk>[0-9]+)/confirm/$', views.MainDelete.as_view(), name='main-delete'),
    url(r'^medicaments/$', views.MedicamentsList.as_view(), name='medicaments-list'),
    url(r'^medicaments/(?P<pk>[0-9]+)/$', views.MedicamentDetail.as_view(), name='medicament-detail'),
    url(r'^medicaments/add/$', views.MedicamentCreate.as_view(), name='medicament-add'),
    url(r'^medicaments/(?P<pk>[0-9]+)/update/$', views.MedicamentUpdate.as_view(), name='medicament-update'),
    url(r'^medicaments/(?P<pk>[0-9]+)/confirm/$', views.MedicamentDelete.as_view(), name='medicament-delete'),
    url(r'^users/login/$', views.login, name='login'),
    url(r'^users/reg/$', views.register, name='register'),
    url(r'^users/forget/$', views.forget_password, name='forget-password'),
    url(r'^users/$', views.UsersList.as_view(), name='users-list'),
    # url(r'^users/create/$', views.UserCreate.as_view(), name='user-create'),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='user-detail'),
    url(r'^users/(?P<pk>[0-9]+)/update/$', views.UserUpdate.as_view(), name='user-update'),
    url(r'^users/(?P<pk>[0-9]+)/confirm/$', views.UserDelete.as_view(), name='user-delete'),
    url(r'^users/(?P<pk>[0-9]+)/change/pass/$', views.UserChangePass.as_view(), name='user-change-password'),
    url(r'^users/(?P<pk>[0-9]+)/change/pass_old/$', views.UserChangePassOld.as_view(), name='user-change-pass-old'),
    url(r'^users/(?P<username>.*)/reset/pass/$', views.UserResetPass.as_view(), name='user-reset-password'),
    url(r'^users/reset/done/', views.UserPassResetDoneView.as_view(), name='user-reset-password-done'),
    url(r'^users/reset/(?P<unameb64>.*)/(?P<token>.*)/', views.UserPasswordResetConfirmView.as_view(), name='user-reset-password-confirm'),
    url(r'^users/reset/complete/', views.PasswordResetCompleteView.as_view(), name='user-reset-password-complete'),
    url(r'^users/logout/$', views.logout, name='logout'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^patients/$', views.PatientsList.as_view(), name='patients-list'),
    url(r'^patients/(?P<pk>[0-9]+)/$', views.PatientDetail.as_view(), name='patient-detail'),
    url(r'^patients/add/$', views.patient_add, name='patient-add'),
    url(r'^patients/(?P<pk>[0-9]+)/update/$', views.PatientUpdate.as_view(), name='patient-update'),
    url(r'^patients/(?P<pk>[0-9]+)/confirm/$', views.PatientDelete.as_view(), name='patient-delete'),
    url(r'^code/$', views.code, name='code')
]

tysk/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.core.exceptions import ObjectDoesNotExist
from django.utils.timezone import now, localtime
from django.core import validators
from django.shortcuts import reverse
from decouple import config


# Власник за замовчуванням - test
def get_default_user():
    try:
        user = User.objects.get(username=config('test'))
    except ObjectDoesNotExist:
        # Немає
        user = User.objects.create_user(config('test'), config('test_email'), config('test_pass'))
        user.first_name = 'В'
        user.last_name = 'Тест паціент'
        user.middle_name = 'В'
        user.is_superuser = False
        user.is_staff = True
        # https://stackoverflow.com/questions/50015204/direct-assignment-to-the-forward-side-of-a-many-to-many-set-is-prohibited-use-e
        user.groups.set(Group.objects.all())
        user.save()
        print('*** test user created in models/get_default_user()! ***')
    return user.pk


# Пацієнти
class Patient(models.Model):
    class Meta:
        verbose_name = 'пацієнт'
        verbose_name_plural = 'пацієнти'

    user = models.OneToOneField(User, verbose_name='користувач', on_delete=models.CASCADE, default=get_default_user(),
                                error_messages={'unique':
                                                'Пацієнт з таким користувачем вже існує. '
                                                'Змініть цього пацієнта або зареєструйте нового користувача.'})
    doctors = models.ManyToManyField('Doctor', verbose_name='лікар')
    male = models.BooleanField(verbose_name='стать', default=True)

    def __str__(self):
        return self.user.last_name

    def get_absolute_url(self):
        return reverse('tysk:patient-detail', kwargs={'pk': self.pk})


# Лікарі
class Doctor(models.Model):
    class Meta:
        verbose_name = 'лікар'
        verbose_name_plural = 'лікарі'

    user = models.OneToOneField(User, verbose_name='користувач', on_delete=models.CASCADE)
    patients = models.ManyToManyField(Patient, verbose_name='паціент')

    def __str__(self):
        return self.user.last_name

    def get_absolute_url(self):
        return reverse('tysk:doctor-detail', kwargs={'pk': self.pk})


# Ліки
class Medicament(models.Model):
    class Meta:
        verbose_name = 'ліки'
        verbose_name_plural = 'ліки'

    name = models.CharField(max_length=200, verbose_name='назва, кількість, дозування...')
    owner = models.ForeignKey(User, verbose_name='власник', default=get_default_user, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tysk:medicament-detail', kwargs={'pk': self.pk})


# Головна
class Main(models.Model):
    class Meta:
        verbose_name = 'головна'
        verbose_name_plural = 'головні'

    patient = models.ForeignKey(Patient, verbose_name='пацієнт', on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, verbose_name='лікар',
                               on_delete=models.CASCADE)  # , help_text='Виберіть лікарів, або значення "Я сам"'
    date = models.DateField('дата вимірювання', default=localtime(now()).date())
    time = models.TimeField('час вимірювання', default=localtime(now()).time())
    upper = models.PositiveSmallIntegerField('верхній',
                                             validators=[validators.MinValueValidator(0),
                                                         validators.MaxValueValidator(300)])
    lower = models.PositiveSmallIntegerField('нижній',
                                             validators=[validators.MinValueValidator(0),
                                                         validators.MaxValueValidator(300)])
    pulse = models.PositiveSmallIntegerField('пульс', blank=True,
                                             validators=[validators.MinValueValidator(0),
                                                         validators.MaxValueValidator(300)])
    medicament = models.ForeignKey(Medicament, verbose_name='ліки', on_delete=models.CASCADE)

    # https://djbook.ru/rel1.9/ref/models/fields.html#default
    # Для полей типа ForeignKey, которые ссылаются на объекты модели, значением по умолчанию должно быть значение поля
    # на которое они ссылаются (pk, если не указан to_field), а не объект модели.
    owner = models.ForeignKey(User, verbose_name='власник', default=get_default_user, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('tysk:main-detail', args=[str(self.pk)])

tysk/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, SetPasswordForm, PasswordChangeForm \
    , PasswordResetForm

from . import models
from django import forms
from django.core import mail
from django.contrib.auth.tokens import default_token_generator
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.contrib.sites.shortcuts import get_current_site


def make_error_not_auth():
    raise forms.ValidationError("Зайдіть в свій профіль, будь ласка.")


class UserForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        del self.fields['password']

    class Meta:
        model = models.User
        fields = ['username', 'first_name', 'last_name', 'email']


class UserSetPasswordForm(SetPasswordForm):
    class Meta:
        model = models.User
        fields = ['password']


class UserChangePasswordForm(PasswordChangeForm):
    class Meta:
        model = models.User
        fields = ['password']


class UserPasswordResetForm(forms.Form):
    template_name = 'tysk/user/user-reset-pass.html'
    email_template_name = 'tysk/user/user-reset-pass-email.html'
    subject_template_name = 'tysk/user/reset_subject.txt'
    from_email = 'noreply@ownsvit.top'
    to_email = ''

    class Meta:
        model = models.User
        fields = ['username', 'email']

    def send_email(self, subject_template_name, email_template_name, context, from_email, to_email,
                   html_email_template_name=None):
        connection = mail.get_connection()
        print('connection', connection)
        if connection.open():
            subject = loader.render_to_string(subject_template_name, context)
            # Email subject *must not* contain newlines
            subject = ''.join(subject.splitlines())
            print('context', context)
            mess = loader.render_to_string(email_template_name, context)
            email1 = mail.EmailMessage(subject, mess, from_email,
                                       [to_email], connection=connection)
            n = email1.send()
            print('n', n)
            connection.close()
        else:
            print('not open(')
            subject = loader.render_to_string(subject_template_name, context)
            # Email subject *must not* contain newlines
            subject = ''.join(subject.splitlines())
            print('context', context)
            mess = loader.render_to_string(email_template_name, context)
            email1 = mail.EmailMessage(subject, mess, from_email,
                                       [to_email], connection=connection)
            n = email1.send()
            print('n', n)

    def save(self, user_object, request):
        print('save')
        username = user_object.username
        print('username', username)
        email = user_object.email
        current_site = get_current_site(request)
        domain = current_site.domain

        context = {'email': email,
                   # 'uname': urlsafe_base64_encode(force_bytes(username)).decode(),
                   'uname': urlsafe_base64_encode(force_bytes(username)),
                   'token': default_token_generator.make_token(user_object),
                   'protocol': 'http',
                   'domain': domain}

        self.send_email(self.subject_template_name, self.email_template_name, context, self.from_email, email)


class TyskUserCreationForm(UserCreationForm):

    class Meta:
        model = models.User
        fields = ['username', 'first_name', 'last_name', 'email', 'groups', 'user_permissions', 'is_staff', 'is_active',
                  'is_superuser']


class RegisterForm(forms.Form):
    GENDER_CHOICES = (
        ('male', 'Чоловіча'),
        ('female', 'Жіноча'),
    )
    TYPE_USER_CHOICES = (
            ('patient', 'Пацієнт'),
            ('doctor', 'Лікар'),
    )
    username = forms.EmailField(label='Електронна пошта')
    password1 = forms.CharField(label='Пароль', help_text='звертайте увагу на мову і регістр', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Підтверження паролю', help_text='', widget=forms.PasswordInput)
    first_name = forms.CharField(label='Ім`я', help_text='ім`я (наприклад - Тарас, Олена)')
    gender = forms.ChoiceField(choices=GENDER_CHOICES, label='Стать', widget=forms.RadioSelect)
    type_user = forms.ChoiceField(choices=TYPE_USER_CHOICES, label='Хто?', widget=forms.RadioSelect)

    def check_passwords_match(self):
        # Check that the two password entries match
        # Визивається в clean
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            # raise forms.ValidationError("Паролі не співпадають")
            return False
        return True

    def clean(self):
        if not self.check_passwords_match():
            super(RegisterForm, self).clean()
            raise forms.ValidationError("Паролі не співпадають")


class IndexForm(forms.Form):
    upper = forms.IntegerField(max_value=300, min_value=0)
    lower = forms.IntegerField(max_value=300, min_value=0)
    pulse = forms.IntegerField(max_value=300, min_value=0)
    email = forms.EmailField()


class ContactForm(forms.Form):
    name = forms.CharField(max_length=50, label='Ім`я:', widget=forms.TextInput(attrs={'class': 'form-control input-lg'
        }), required=False)
    email = forms.EmailField(label='Ваша електронна пошта:', widget=forms.EmailInput(attrs={'class': 'form-control input-lg'}))
    message = forms.CharField(label='', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5',
        'placeholder': 'Повідомлення'}))


class MedicamentCreateForm(forms.ModelForm):
    class Meta:
        model = models.Medicament
        fields = ['name', 'owner']
        widgets = {'owner': forms.HiddenInput}


class MedicamentSuperUserCreateForm(forms.ModelForm):
    class Meta:
        model = models.Medicament
        fields = ['name', 'owner']


class MedicamentUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Medicament
        fields = ['name', 'owner']
        widgets = {'owner': forms.HiddenInput}


class MedicamentSuperUserUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Medicament
        fields = ['name', 'owner']


class PatientCreateForm(forms.ModelForm):
    GENDER_CHOICES = (
        (True, 'Чол'),
        (False, 'Жін '),
    )
    male = forms.ChoiceField(choices=GENDER_CHOICES, label='Стать', widget=forms.RadioSelect())

    class Meta:
        model = models.Patient
        fields = ['doctors', 'male', 'user']
        widgets = {'user': forms.HiddenInput}


class PatientSuperUserCreateForm(PatientCreateForm):
    print('dir(PatientCreateForm)', dir(PatientCreateForm))
    # male = PatientCreateForm.male

    class Meta:
        model = models.Patient
        fields = ['user', 'doctors', 'male']


class PatientUpdateForm(forms.ModelForm):
    GENDER_CHOICES = (
        (True, 'Чол'),
        (False, 'Жін '),
    )
    male = forms.ChoiceField(choices=GENDER_CHOICES, label='Стать', widget=forms.RadioSelect())

    class Meta:
        model = models.Patient
        fields = ['doctors', 'male', 'user']
        widgets = {'user': forms.HiddenInput}


class PatientSuperUserUpdateForm(PatientUpdateForm):

    class Meta:
        model = models.Patient
        fields = ['user', 'doctors', 'male']


class DoctorCreateForm(forms.ModelForm):

    class Meta:
        model = models.Doctor
        fields = ['patients', 'user']
        widgets = {'user': forms.HiddenInput}


class DoctorSuperUserCreateForm(DoctorCreateForm):

    class Meta:
        model = models.Doctor
        fields = ['user', 'patients']


class DoctorUpdateForm(forms.ModelForm):

    class Meta:
        model = models.Doctor
        fields = ['patients', 'user']
        widgets = {'user': forms.HiddenInput}


class DoctorSuperUserUpdateForm(DoctorUpdateForm):

    class Meta:
        model = models.Doctor
        fields = ['user', 'patients']


class PatientChooseMainForm(forms.ModelForm):

    patient = forms.ModelChoiceField(queryset=models.Patient.objects.get_queryset(), label='по пацієнту')

    class Meta:
        model = models.Main
        fields = ['patient']

tysk/templates/tysk/main/main-detail.html
{% extends 'tysk/index.html' %}
{% load static %}
{% block title %}Тиск - Головна - Деталі{% endblock %}
{% block header %}
    <!-- Site header -->
    <header class="page-header bg-img size-lg" style="background-image: url({% static 'tysk/img/bg-banner2.jpg' %})">
      <div class="container no-shadow">
        <h1 class="text-center">Головна</h1>
        <p class="lead text-center">{{ main.patient }}</p>
      </div>
    </header>
    <!-- END Site header -->
{% endblock %}
{% block content %}
<main>
    <div class="container login-block">
        <img src="{% static 'tysk/img/logo.jpg' %}" id="click-me" alt="">

        <h5></h5>
        <p>            Пацієнт - {{ main.patient }}        </p>
        <p>Доктор - {{ main.doctor}}</p>
        <p>Дата - {{ main.date}}</p>
        <p>Час - {{ main.time}}</p>
        <p>Верхній тиск - {{ main.upper}}</p>
        <p>Нижній - {{ main.lower}}</p>
        <p>Пульс - {{ main.pulse}}</p>
        <p>Ліки - {{ main.medicament}}</p>
        {% if user.is_superuser %}
            <p>Власник - {{ main.owner }}</p>
        {% endif %}
        <div><a class="btn btn-success" href="{% url 'tysk:main-update' object.id %}">Змінити</a> </div>
    </div>

      <div class="container login-links">
        <p class="text-center"><a href="{% url 'tysk:index' %}">На початкову</a></p>
      </div>
</main>
{% endblock content %}
{% block script %}
    {{ block.super }}
{% endblock %}
</body>

tysk/templates/tysk/main/mains-list.html
{% extends 'tysk/index.html' %}
{% load static %}
{% block title %}Тиск - Головна - Список{% endblock %}
{% block header %}
    <!-- Site header -->
{#    <header class="page-header bg-img size-lg" style="background-image: url({% static 'tysk/img/bg-banner2.jpg' %})">#}
    <header class="page-header bg-img">
      <div class="container no-shadow">
        <h4 class="text-center">Головний список</h4>
        <p class="text-center">
{#            {{ form }}#}
            Бажаємо Вам здоров`я!</p>
          {% if user.is_authenticated %}
              <p class="text-center">
              {% for patient in patients %}
                  {% if is_doctor_filter %}
                      <a href="?patient={{ patient.id }}&doctor={{ request.sesion.doctor_filter }}"
                         title="Фільтр по паціенту">{{ patient }}</a>
                  {% else %}
                      <a href="?patient={{ patient.id }}" title="Фільтр по паціенту">{{ patient }}</a>
                  {% endif %}
                {% endfor %}

                {% if patient_paginated %}
                    <span aria-label="patients pagination">
                        <span class="pagination">
                          {% if patients.has_previous %}
                            <span class="page-item">
                              <a class="page-link" href="?page_patient={{ patients.previous_page_number }}"
                                 title="Попередній"> < </a>
                            </span>
                          {% else %}
                            <span class="page-item disabled">
                              <span class="page-link" title="Початок списку"><</span>
                            </span>
                          {% endif %}

                          {% if patients.has_next %}
                            <span class="page-item">
                              <a class="page-link" href="?page_patient={{ patients.next_page_number }}"
                                 title="Наступний">></a>
                            </span>
                          {% else %}
                            <span class="page-item disabled">
                              <span class="page-link" title="Список закінчився"> > </span>
                            </span>
                          {% endif %}
                        </span>
                    </span> <a href="?patient=X">X</a> <br>
                {% else %}
                    {% if active == 'mains-list-filter' %}
                        <a href="?patient=X">X</a> <hr class="no-margin">
                    {% endif %}
                {% endif %}
              </p>
                <p class="text-center">
                    {% for doctor in doctors %}
                        {% if is_patient_filter %}
                            <a href="?doctor={{ doctor.id }}&patient={{ request.session.patient_filter }}">{{ doctor }}
                            </a>
                        {% else %}
                            <a href="?doctor={{ doctor.id }}" title="Фільтр по лікарю">
                            {{ doctor }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if doctor_paginated %}
                        <span aria-label="doctorss pagination">
                            <span class="pagination">
                                {% if doctors.has_previous %}
                                    <span class="page-item">
                                        <a class="page-link" href="?page_doctor={{ doctors.previous_page_number }}"
                                        title="Попередній">
                                            <
                                        </a>
                                    </span>
                                {% else %}
                                    <span class="page-item disabled">
                                      <span class="page-link" title="Початок списку"><</span>
                                    </span>
                                {% endif %}
                                {% if doctors.has_next %}
                                    <span class="page-item">
                                        <a class="page-link" href="?page_doctor={{ doctors.next_page_number }}"
                                           title="Наступний">
                                            >
                                        </a>
                                    </span>
                                {% else %}
                                    <span class="page-item disabled">
                                      <span class="page-link" title="Список закінчився"> > </span>
                                    </span>
                                {% endif %}
                            </span>
                        </span>
                    {% endif %}
                    {% if active == 'mains-list-filter' %}
                        <a href="?doctor=X">X</a>
                    {% endif %}
                </p>
          {% endif %}
      </div>

    </header>
    <!-- END Site header -->
{% endblock %}
{% block content %}
    <!-- Main container -->
    <main>
      <!--  -->
      <section style="padding: 4px 2px">

          <div class="container login-block">
            {% if user.is_authenticated %}

            {% if main_list %}

                <span id="result">
                    {% for main_item in main_list %}
                    <a class="col-xs-10 col-sm-10" href="{% url 'tysk:main-detail' main_item.id %}" title="{{ main_item.medicament }}">
                        <span class="col-xs-2 col-sm-2"> {{ main_item.patient }} </span>
                        <span class="col-xs-2 col-sm-2"> {{ main_item.doctor }} </span>
                        <span class="col-xs-2 col-sm-2">{{ main_item.date|date:'d.m.Y' }} </span>
                        <span class="col-xs-2 col-sm-2">{{ main_item.time }}</span>
                        <span class="col-xs-2 col-sm-2" title="Верхній, нижній та пульс">{{ main_item.upper }} {{ main_item.lower }} {{ main_item.pulse }}</span>

                    </a>
                    <span class="col-xs-2 col-sm-1">
                        <a class="btn btn-success btn-outline btn-xs" href="{% url 'tysk:main-update' main_item.id %}">
                            Змінити
                        </a>
                    </span>
                    <span class="col-xs-2 col-sm-1">
                        <a class="btn btn-danger btn-outline btn-xs" href="{% url 'tysk:main-delete' main_item.id %}">
                            Видалити
                        </a>
                    </span>
                {% endfor %}
{#                {% show_more %}#}
                {% if is_paginated %}
                    <nav aria-label="Mains pagination" class="mb-4">
                        <ul class="pagination">
                          {% if page_obj.has_previous %}
                            <li class="page-item">
                              <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                            </li>
                          {% else %}
                            <li class="page-item disabled">
                              <span class="page-link">Previous</span>
                            </li>
                          {% endif %}

                          {% for page_num in paginator.page_range %}
                            {% if page_obj.number == page_num %}
                              <li class="page-item active">
                                <span class="page-link">
                                  {{ page_num }}
                                  <span class="sr-only">(current)</span>
                                </span>
                              </li>
                            {% else %}
                              <li class="page-item">
                                <a class="page-link" href="?page={{ page_num }}{{ session_parameters_string }}">{{ page_num }}</a>
                              </li>
                            {% endif %}
                          {% endfor %}

                          {% if page_obj.has_next %}
                            <li class="page-item">
                              <a class="page-link" href="?page_ajax={{ page_obj.next_page_number }}">Next</a>
                            </li>
                          {% else %}
                            <li class="page-item disabled">
                              <span class="page-link">Next</span>
                            </li>
                          {% endif %}
                        </ul>
                    </nav>
                {% endif %}
                </span>
{#                <span id="result">    {% include page_template %}</span>#}

{#                {% include 'tysk/includes/pagination.html' %}#}
            {% else %}
                <img src="{% static 'tysk/img/sad.jpg' %}" id="click-me" alt="">
                <p>Немає даних.
            {% endif %}
            {% else %}
                <header class="section-header">
                    <span>Ви не ввійшли</span>
                </header>
            {% endif %} {# {% if user.is_authenticated %} #}
          </div>
      </section>
      <div class="container login-links">
        <p class="text-center"><a href="{% url 'tysk:index' %}">На початкову</a></p>
      </div>
    </main>
    <!-- END Main container -->
{% endblock content %}
</body>
{% block script %}
    {{ block.super }}
    <script>
        var data = {"filter_value":'', "page": '1'};
        var data_click = {"page_ajax": "1", "filter_value": $('#id_patient option:selected').val()};
        console.log('before data_click.filter_value:');
        console.log(data_click.filter_value);
        if (typeof data_click.filter_value == 'undefined'){data_click.filter_value = ''}
        console.log(data_click.filter_value);
        $(function () {
    {#            изменение #}
        $('#id_patient').on("change", function () {
    {#                alert(data.order);#}
            data.filter_value = this.value;
            console.log('data.filter_value', data.filter_value);
            data.page = '1';
            $.get("{% url 'tysk:mains-list' %}", data, filterVal, "json");
        });
        function filterVal (patient_list_ajax) {
            $('#result').html(patient_list_ajax.html);
    {#        $("#what_search").text(employees_list_ajax.search);#}
    {#        $("#what_sort").text(employees_list_ajax.order);#}
        }
        });
        function js_paginator(page_num, patient_filter) {
            data_click.page_ajax = page_num;
            data_click.filter_value = patient_filter;

            if (typeof patient_filter != 'undefined'){
                console.log('patient_filter != undefined');
                $.get("{% url 'tysk:mains-list' %}?page_ajax="+page_num+"&filter_value="+patient_filter,
                    data_click, filterValPaginator, "json");}
            else
            {
                console.log('patient_filter == undefined!');
                $.get("{% url 'tysk:mains-list' %}?page="+page_num+"&page_ajax="+page_num,
                    data_click, filterValPaginator, "json");}
            {#$.get("{% url 'tysk:mains-list' %}?filter_value="+patient_filter, data_click, filterValPaginator, "json");#}
        }
        function filterValPaginator (patient_list_ajax) {
            $('#result').html(patient_list_ajax.html);
            console.log("in function filterValPaginator");
            alert("in function filterValPaginator");
    {#        $("#what_search").text(employees_list_ajax.search);#}
    {#        $("#what_sort").text(employees_list_ajax.order);#}
        }
    </script>
{#    <script src="{{ STATIC_URL }}el-pagination/js/el-pagination.js"></script>#}
    <script src="{% static 'el-pagination/js/el-pagination.js' %}"></script>
    <script>$.endlessPaginate({
            onClick: function(context) {
                console.log('Label:', $(this).text());
                console.log('URL:', context.url);
                console.log('Querystring key:', context.key);
                if (forbidden) {  // to be defined...
                    return false;
                }
            },
            onCompleted: function(context, fragment) {
                console.log('Label:', $(this).text());
                console.log('URL:', context.url);
                console.log('Querystring key:', context.key);
                console.log('Fragment:', fragment);
            }
        });</script>
{% endblock %}