itysk/urls.py
from django.conf.urls import url, include
from django.contrib import admin as tysk_admin

urlpatterns = [
    url(r'^tysk/admin/', tysk_admin.site.urls),
    # https://stackoverflow.com/questions/48608894/specifying-a-namespace-in-include-without-providing-an-app-name
    # url(r'^tysk/', include('tysk.urls', namespace="tysk")),
    url(r'^tysk/', include(('tysk.urls', 'tysk'), namespace="tysk")),
    url(r'^tysk/accounts/', include('allauth.urls')),
]

tysk/urls.py
from django.conf.urls import url
from tysk import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^doctors/$', views.DoctorsList.as_view(), name='doctors-list'),
    url(r'^doctors/(?P<pk>[0-9]+)/$', views.DoctorDetail.as_view(), name='doctor-detail'),
    url(r'^doctors/add/$', views.doctor_add, name='doctor-add'),
    url(r'^doctors/(?P<pk>[0-9]+)/update/$', views.DoctorUpdate.as_view(), name='doctor-update'),
    url(r'^doctors/(?P<pk>[0-9]+)/confirm/$', views.DoctorDelete.as_view(), name='doctor-delete'),
    url(r'^mains/$', views.MainsList.as_view(), name='mains-list'),
    url(r'^mainsget/$', views.main_filter, name='main-filter'),
    url(r'^mains/(?P<pk>[0-9]+)/$', views.MainDetail.as_view(), name='main-detail'),
    url(r'^mains/add/$', views.MainCreate.as_view(), name='main-add'),
    url(r'^mains/(?P<pk>[0-9]+)/update/$', views.MainUpdate.as_view(), name='main-update'),
    url(r'^mains/(?P<pk>[0-9]+)/confirm/$', views.MainDelete.as_view(), name='main-delete'),
    url(r'^medicaments/$', views.MedicamentsList.as_view(), name='medicaments-list'),
    url(r'^medicaments/(?P<pk>[0-9]+)/$', views.MedicamentDetail.as_view(), name='medicament-detail'),
    url(r'^medicaments/add/$', views.MedicamentCreate.as_view(), name='medicament-add'),
    url(r'^medicaments/(?P<pk>[0-9]+)/update/$', views.MedicamentUpdate.as_view(), name='medicament-update'),
    url(r'^medicaments/(?P<pk>[0-9]+)/confirm/$', views.MedicamentDelete.as_view(), name='medicament-delete'),
    url(r'^users/login/$', views.login, name='login'),
    url(r'^users/reg/$', views.register, name='register'),
    url(r'^users/forget/$', views.forget_password, name='forget-password'),
    url(r'^users/$', views.UsersList.as_view(), name='users-list'),
    # url(r'^users/create/$', views.UserCreate.as_view(), name='user-create'),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='user-detail'),
    url(r'^users/(?P<pk>[0-9]+)/update/$', views.UserUpdate.as_view(), name='user-update'),
    url(r'^users/(?P<pk>[0-9]+)/confirm/$', views.UserDelete.as_view(), name='user-delete'),
    url(r'^users/(?P<pk>[0-9]+)/change/pass/$', views.UserChangePass.as_view(), name='user-change-password'),
    url(r'^users/(?P<pk>[0-9]+)/change/pass_old/$', views.UserChangePassOld.as_view(), name='user-change-pass-old'),
    url(r'^users/(?P<username>.*)/reset/pass/$', views.UserResetPass.as_view(), name='user-reset-password'),
    url(r'^users/reset/done/', views.UserPassResetDoneView.as_view(), name='user-reset-password-done'),
    url(r'^users/reset/(?P<unameb64>.*)/(?P<token>.*)/', views.UserPasswordResetConfirmView.as_view(), name='user-reset-password-confirm'),
    url(r'^users/reset/complete/', views.PasswordResetCompleteView.as_view(), name='user-reset-password-complete'),
    url(r'^users/logout/$', views.logout, name='logout'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^patients/$', views.PatientsList.as_view(), name='patients-list'),
    url(r'^patients/(?P<pk>[0-9]+)/$', views.PatientDetail.as_view(), name='patient-detail'),
    url(r'^patients/add/$', views.patient_add, name='patient-add'),
    url(r'^patients/(?P<pk>[0-9]+)/update/$', views.PatientUpdate.as_view(), name='patient-update'),
    url(r'^patients/(?P<pk>[0-9]+)/confirm/$', views.PatientDelete.as_view(), name='patient-delete'),
    url(r'^code/$', views.code, name='code')
]

tysk/views.py
from django.contrib.auth import authenticate, login as auth_login, \
    logout as auth_logout  # http://stackoverflow.com/questions/39316948/
from django.contrib.auth.models import User, Group
from django.core.exceptions import ObjectDoesNotExist
from django.utils.datastructures import MultiValueDictKeyError
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
# typeerror-login-takes-1-positional-argument-but-2-were-given
from django.utils.timezone import now, localtime
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse
from itysk import settings
from decouple import config

from . import forms
from . import models
from .utilities import which_invoked
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.http import is_safe_url, urlsafe_base64_decode
from django.core.exceptions import ValidationError
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.template.loader import render_to_string
from django.contrib.sites.models import Site
from django.db.models import Q
import json
from el_pagination.views import AjaxListView
from django.views.generic.list import MultipleObjectMixin, TemplateResponseMixin, View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def auth_or_create(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                # Redirect to a success page.
            else:
                # Return a 'disabled account' error message
                pass
        else:
            # Return an 'invalid login' error message.
            pass
    if not request.user.is_authenticated:
        create_user_self(request)
    return context


def index(request):
    # початкова
    context = {'active': 'index'}
    number_of_users = [ number_of_users for number_of_users in range(919, 1149)]
    context['number_of_users'] = number_of_users
    user = request.user
    if not request.user.is_authenticated:
        create_user_self(request)
        print("create_user_self виконано!")
    if request.method == 'POST':
        main_form = forms.IndexForm(request.POST)
        upper = request.POST['upper']
        lower = request.POST['lower']
        pulse = request.POST['pulse']
        email = request.POST['email']
        context['main_form'] = main_form
        if not request.user.is_authenticated and 'database_save' in main_form.data:
            forms.make_error_not_auth()  # додаємо помилку
        if main_form.is_valid():
            if 'send_email' in main_form.data:
                print('send_email !')
                from django.core import mail
                connection = mail.get_connection()
                if connection.open():
                    there = '\n Поскаржитись на цей лист можна тут www.ownsvit.top/tysk/contact/ '
                        # {'protocol': 'https://', 'domain': Site.objects.get_current(request).domain})
                    subject = 'Тиск. www.ownsvit.top/tysk/. Дата: ' + str(localtime().date()) + ', час ' + str(localtime().time())
                    mess = 'Вітаю! \nЦей лист прийшов Вам з сайту www.ownsvit.top/tysk/ . Верхній тиск: ' + str(upper) + \
                        ', нижній ' + str(lower) + ', пульс ' + str(pulse) + '.\n З повагою, команда Тиск.'
                    email1 = mail.EmailMessage(subject, mess + there, 'postmaster@ownsvit.top',
                                               [email], connection=connection)
                    # email1.attach_alternative(mess + there, 'text/html')
                    email1.send()
                    connection.close()
                    print(':-)')
                return render(request, 'tysk/index.html', context)
            # Створюємо main
            main = models.Main()
            # Шукаємо паціента
            try:
                patient = models.Patient.objects.get(user=user)
            except ObjectDoesNotExist:
                patient = models.Patient()
                patient.user = user
                patient.male = True
                patient.save()
                self_user = User.objects.get(username=config('self'))
                try:
                    self_doctor = models.Doctor.objects.get(user=self_user)
                except ObjectDoesNotExist:
                    self_doctor = models.Doctor()
                    self_doctor.user = self_user
                    self_doctor.save()
                    test_user = User.objects.get(username=config('test'))
                    try:
                        test_patient = models.Patient.objects.get(user=test_user)
                    except ObjectDoesNotExist:
                        test_patient = models.Patient()
                        test_patient.user = test_user
                        test_patient.male = True
                        test_patient.save()
                        print('*** test user created in views/index()! ***')
                        test_patient.doctors.add(self_doctor)
                patient.doctors.add(self_doctor)
            main.patient = patient
            # Шукаємо доктора
            if not patient.doctors.exists():
                self_user = User.objects.get(username=config('self'))
                self_doctor = models.Doctor.objects.get(user=self_user)
                patient.doctors.add(self_doctor)
            doctor = patient.doctors.all()[0]
            main.doctor = doctor
            main.upper = main_form.cleaned_data.get('upper')
            main.lower = main_form.cleaned_data.get('lower')
            main.pulse = main_form.cleaned_data.get('pulse')
            # main.date default - current
            # main.time default - current
            # Шукаємо ліки
            try:
                medicament = models.Medicament.objects.get(name='Не приймали')
            except ObjectDoesNotExist:
                medicament = models.Medicament()
                medicament.name = 'Не приймали'
                medicament.save()
                print('Ліки створено!')
            main.medicament = medicament
            main.owner = user
            main.save()
            # return HttpResponse('First go...')
            return redirect(main)
        else:
            main_form = forms.IndexForm(request.POST)
            print(request.POST)
            context['main_form'] = main_form
            context['upper'] = upper
            context['lower'] = lower
            context['pulse'] = pulse
            context['email'] = email
        return render(request, 'tysk/index.html', context)
    else:
        if user.is_authenticated:
            main_form = forms.IndexForm(initial={'email': user.email, 'pulse': '60'})
            if user.is_superuser:
                context['is_superuser'] = 'is_superuser'
                main_list = models.Main.objects.order_by('-date', '-time')[:5]
            else:
                main_list = models.Main.objects.filter(owner=user)
                """
                try:
                    # чи пацієнт
                    current_patient = models.Patient.objects.get(user=request.user)
                    main_list = models.Main.objects.filter(patient=current_patient).order_by('-date', '-time')[:5]
                except ObjectDoesNotExist:
                    # чи доктор
                    current_doctor = models.Doctor.objects.get(user=request.user)
                    main_list = models.Main.objects.filter(doctor=current_doctor).order_by('-date', '-time')[:5]
                """
        else:
            main_form = forms.IndexForm(initial={'pulse': '60'})
            main_list = []
        context['main_form'] = main_form
        context['main_list'] = main_list
        return render(request, 'tysk/index.html', context)


def create_user_self(request):
    # створення користувача "Суперюзер" при впровадженні
    try:
        user = User.objects.get(username=config('suser'))
    except ObjectDoesNotExist:
        # Немає
        user = User.objects.create_superuser(config('suser'), config('suser_email'), config('suser_pass'))
        user.first_name = 'В'
        user.last_name = 'Суперюзер'
        user.middle_name = 'В'
        user.groups.set(Group.objects.all())
        user.save()
    # створення користувача "Я сам лікар)" при впровадженні
    try:
        user = User.objects.get(username=config('self'))
    except ObjectDoesNotExist:
        # Немає
        user = User.objects.create_user(config('self'), config('self_email'), config('self_pass'))
        user.first_name = 'В'
        user.last_name = 'Я сам лікар)'
        user.middle_name = 'В'
        user.is_superuser = False
        user.is_staff = True
        user.groups.set(Group.objects.all())
        user.save()
    # створення користувача "Тест паціент" при впровадженні
    try:
        user = User.objects.get(username=config('test'))
    except ObjectDoesNotExist:
        # Немає
        user = User.objects.create_user(config('test'), config('test_email'), config('test_pass'))
        user.first_name = 'В'
        user.last_name = 'Тест паціент'
        user.middle_name = 'В'
        user.is_superuser = False
        user.is_staff = True
        user.groups.set(Group.objects.all())
        user.save()
        print('*** test user created in views/create_user_self()! ***')
    try:

tysk/templates/tysk/includes/list_ajax.html
{#{% load el_pagination_tags %}#}
{#                {% paginate main_list %}#}
                {% for main_item in main_list %}
                    <a class="col-xs-10 col-sm-10" href="{% url 'tysk:main-detail' main_item.id %}" title="{{ main_item.medicament }}">
                        <span class="col-xs-2 col-sm-2"> {{ main_item.patient }} </span>
                        <span class="col-xs-2 col-sm-2"> {{ main_item.doctor }} </span>
                        <span class="col-xs-2 col-sm-2">{{ main_item.date|date:'d.m.Y' }} </span>
                        <span class="col-xs-2 col-sm-2">{{ main_item.time }}</span>
                        <span class="col-xs-2 col-sm-2" title="Верхній, нижній та пульс">{{ main_item.upper }} {{ main_item.lower }} {{ main_item.pulse }}</span>

                    </a>
                    <span class="col-xs-2 col-sm-1">
                        <a class="btn btn-success btn-outline btn-xs" href="{% url 'tysk:main-update' main_item.id %}">
                            Змінити
                        </a>
                    </span>
                    <span class="col-xs-2 col-sm-1">
                        <a class="btn btn-danger btn-outline btn-xs" href="{% url 'tysk:main-delete' main_item.id %}">
                            Видалити
                        </a>
                    </span>
                {% endfor %}
{#                {% show_more %}#}
{#                {% include 'tysk/includes/pagination.html' %}#}
is_paginated: {{ is_paginated }}<br> paginator: {{ paginator }}
{% if is_paginated %}
              <nav aria-label="Mains pagination" class="mb-4">
                <ul class="pagination">
                  {% if page_obj.has_previous %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                  {% else %}
                    <li class="page-item disabled">
                      <span class="page-link">Previous</span>
                    </li>
                  {% endif %}

                  {% for page_num in paginator.page_range %}
                    {% if page_obj.number == page_num %}
                      <li class="page-item active">
                        <span class="page-link">
                          {{ page_num }}
                          <span class="sr-only">(current)</span>
                        </span>
                      </li>
                    {% else %}
                      <li class="page-item">
                        <button class="page-link"
{#                           href="?page={{ page_num }}{{ part_ajax_page_link }}" onclick="">#}
{#                           href="?page_ajax={{ page_num }}{{ part_ajax_page_link }}"#}
                           onclick="js_paginator({{ page_num }}, {{ patient_filter }})">
                            {{ page_num }}
                        </button>
                      </li>
                    {% endif %}
                  {% endfor %}

                  {% if page_obj.has_next %}
                    <li class="page-item">
                      <a class="page-link" href="?page_ajax={{ page_obj.next_page_number }}">Next</a>
                    </li>
                  {% else %}
                    <li class="page-item disabled">
                      <span class="page-link">Next</span>
                    </li>
                  {% endif %}
                </ul>
              </nav>
            {% endif %}
<script>
    function js_paginator(page_num, patient_filter) {
            data_click.page_ajax = page_num;
            data_click.filter_value = patient_filter;
            if (patient_filter != undefined){
                $.get("{% url 'tysk:mains-list' %}?page_ajax="+page_num+"&filter_value="+patient_filter,
                    data_click, filterValPaginator, "json");}
            else
            {
                $.get("{% url 'tysk:mains-list' %}?page="+page_num,
                    data_click, filterValPaginator, "json");}
            }
            {#$.get("{% url 'tysk:mains-list' %}?filter_value="+patient_filter, data_click, filterValPaginator, "json");#}
        }
        function filterValPaginator (patient_list_ajax) {
            $('#result').html(patient_list_ajax.html);
            console.log("in function filterValPaginator");
            alert("in function filterValPaginator");
    {#        $("#what_search").text(employees_list_ajax.search);#}
    {#        $("#what_sort").text(employees_list_ajax.order);#}
        }
</script>

tysk/templates/tysk/includes/pagination.html
            {% if is_paginated %}
              <nav aria-label="Mains pagination" class="mb-4">
                <ul class="pagination">
                  {% if page_obj.has_previous %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                  {% else %}
                    <li class="page-item disabled">
                      <span class="page-link">Previous</span>
                    </li>
                  {% endif %}

                  {% for page_num in paginator.page_range %}
                    {% if page_obj.number == page_num %}
                      <li class="page-item active">
                        <span class="page-link">
                          {{ page_num }}
                          <span class="sr-only">(current)</span>
                        </span>
                      </li>
                    {% else %}
                      <li class="page-item">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                      </li>
                    {% endif %}
                  {% endfor %}

                  {% if page_obj.has_next %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                  {% else %}
                    <li class="page-item disabled">
                      <span class="page-link">Next</span>
                    </li>
                  {% endif %}
                </ul>
              </nav>
            {% endif %}