itysk/urls.py
from django.conf.urls import url, include
from django.contrib import admin as tysk_admin

urlpatterns = [
    url(r'^tysk/admin/', tysk_admin.site.urls),
    # https://stackoverflow.com/questions/48608894/specifying-a-namespace-in-include-without-providing-an-app-name
    # url(r'^tysk/', include('tysk.urls', namespace="tysk")),
    url(r'^tysk/', include(('tysk.urls', 'tysk'), namespace="tysk")),
    url(r'^tysk/accounts/', include('allauth.urls')),
]

tysk/urls.py
from django.conf.urls import url
from tysk import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^doctors/$', views.DoctorsList.as_view(), name='doctors-list'),
    url(r'^doctors/(?P<pk>[0-9]+)/$', views.DoctorDetail.as_view(), name='doctor-detail'),
    url(r'^doctors/add/$', views.doctor_add, name='doctor-add'),
    url(r'^doctors/(?P<pk>[0-9]+)/update/$', views.DoctorUpdate.as_view(), name='doctor-update'),
    url(r'^doctors/(?P<pk>[0-9]+)/confirm/$', views.DoctorDelete.as_view(), name='doctor-delete'),
    url(r'^mains/$', views.MainsList.as_view(), name='mains-list'),
    url(r'^mainsget/$', views.main_filter, name='main-filter'),
    url(r'^mains/(?P<pk>[0-9]+)/$', views.MainDetail.as_view(), name='main-detail'),
    url(r'^mains/add/$', views.MainCreate.as_view(), name='main-add'),
    url(r'^mains/(?P<pk>[0-9]+)/update/$', views.MainUpdate.as_view(), name='main-update'),
    url(r'^mains/(?P<pk>[0-9]+)/confirm/$', views.MainDelete.as_view(), name='main-delete'),
    url(r'^medicaments/$', views.MedicamentsList.as_view(), name='medicaments-list'),
    url(r'^medicaments/(?P<pk>[0-9]+)/$', views.MedicamentDetail.as_view(), name='medicament-detail'),
    url(r'^medicaments/add/$', views.MedicamentCreate.as_view(), name='medicament-add'),
    url(r'^medicaments/(?P<pk>[0-9]+)/update/$', views.MedicamentUpdate.as_view(), name='medicament-update'),
    url(r'^medicaments/(?P<pk>[0-9]+)/confirm/$', views.MedicamentDelete.as_view(), name='medicament-delete'),
    url(r'^users/login/$', views.login, name='login'),
    url(r'^users/reg/$', views.register, name='register'),
    url(r'^users/forget/$', views.forget_password, name='forget-password'),
    url(r'^users/$', views.UsersList.as_view(), name='users-list'),
    # url(r'^users/create/$', views.UserCreate.as_view(), name='user-create'),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='user-detail'),
    url(r'^users/(?P<pk>[0-9]+)/update/$', views.UserUpdate.as_view(), name='user-update'),
    url(r'^users/(?P<pk>[0-9]+)/confirm/$', views.UserDelete.as_view(), name='user-delete'),
    url(r'^users/(?P<pk>[0-9]+)/change/pass/$', views.UserChangePass.as_view(), name='user-change-password'),
    url(r'^users/(?P<pk>[0-9]+)/change/pass_old/$', views.UserChangePassOld.as_view(), name='user-change-pass-old'),
    url(r'^users/(?P<username>.*)/reset/pass/$', views.UserResetPass.as_view(), name='user-reset-password'),
    url(r'^users/reset/done/', views.UserPassResetDoneView.as_view(), name='user-reset-password-done'),
    url(r'^users/reset/(?P<unameb64>.*)/(?P<token>.*)/', views.UserPasswordResetConfirmView.as_view(), name='user-reset-password-confirm'),
    url(r'^users/reset/complete/', views.PasswordResetCompleteView.as_view(), name='user-reset-password-complete'),
    url(r'^users/logout/$', views.logout, name='logout'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^patients/$', views.PatientsList.as_view(), name='patients-list'),
    url(r'^patients/(?P<pk>[0-9]+)/$', views.PatientDetail.as_view(), name='patient-detail'),
    url(r'^patients/add/$', views.patient_add, name='patient-add'),
    url(r'^patients/(?P<pk>[0-9]+)/update/$', views.PatientUpdate.as_view(), name='patient-update'),
    url(r'^patients/(?P<pk>[0-9]+)/confirm/$', views.PatientDelete.as_view(), name='patient-delete'),
    url(r'^code/$', views.code, name='code')
]

tysk/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.core.exceptions import ObjectDoesNotExist
from django.utils.timezone import now, localtime
from django.core import validators
from django.shortcuts import reverse
from decouple import config


# Власник за замовчуванням - test
def get_default_user():
    try:
        user = User.objects.get(username=config('test'))
    except ObjectDoesNotExist:
        # Немає
        user = User.objects.create_user(config('test'), config('test_email'), config('test_pass'))
        user.first_name = 'В'
        user.last_name = 'Тест паціент'
        user.middle_name = 'В'
        user.is_superuser = False
        user.is_staff = True
        # https://stackoverflow.com/questions/50015204/direct-assignment-to-the-forward-side-of-a-many-to-many-set-is-prohibited-use-e
        user.groups.set(Group.objects.all())
        user.save()
        print('*** test user created in models/get_default_user()! ***')
    return user.pk


# Пацієнти
class Patient(models.Model):
    class Meta:
        verbose_name = 'пацієнт'
        verbose_name_plural = 'пацієнти'

    user = models.OneToOneField(User, verbose_name='користувач', on_delete=models.CASCADE, default=get_default_user(),
                                error_messages={'unique':
                                                'Пацієнт з таким користувачем вже існує. '
                                                'Змініть цього пацієнта або зареєструйте нового користувача.'})
    doctors = models.ManyToManyField('Doctor', verbose_name='лікар')
    male = models.BooleanField(verbose_name='стать', default=True)

    def __str__(self):
        return self.user.last_name

    def get_absolute_url(self):
        return reverse('tysk:patient-detail', kwargs={'pk': self.pk})


# Лікарі
class Doctor(models.Model):
    class Meta:
        verbose_name = 'лікар'
        verbose_name_plural = 'лікарі'

    user = models.OneToOneField(User, verbose_name='користувач', on_delete=models.CASCADE)
    patients = models.ManyToManyField(Patient, verbose_name='паціент')

    def __str__(self):
        return self.user.last_name

    def get_absolute_url(self):
        return reverse('tysk:doctor-detail', kwargs={'pk': self.pk})


# Ліки
class Medicament(models.Model):
    class Meta:
        verbose_name = 'ліки'
        verbose_name_plural = 'ліки'

    name = models.CharField(max_length=200, verbose_name='назва, кількість, дозування...')
    owner = models.ForeignKey(User, verbose_name='власник', default=get_default_user, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tysk:medicament-detail', kwargs={'pk': self.pk})


# Головна
class Main(models.Model):
    class Meta:
        verbose_name = 'головна'
        verbose_name_plural = 'головні'

    patient = models.ForeignKey(Patient, verbose_name='пацієнт', on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, verbose_name='лікар',
                               on_delete=models.CASCADE)  # , help_text='Виберіть лікарів, або значення "Я сам"'
    date = models.DateField('дата вимірювання', default=localtime(now()).date())
    time = models.TimeField('час вимірювання', default=localtime(now()).time())
    upper = models.PositiveSmallIntegerField('верхній',
                                             validators=[validators.MinValueValidator(0),
                                                         validators.MaxValueValidator(300)])
    lower = models.PositiveSmallIntegerField('нижній',
                                             validators=[validators.MinValueValidator(0),
                                                         validators.MaxValueValidator(300)])
    pulse = models.PositiveSmallIntegerField('пульс', blank=True,
                                             validators=[validators.MinValueValidator(0),
                                                         validators.MaxValueValidator(300)])
    medicament = models.ForeignKey(Medicament, verbose_name='ліки', on_delete=models.CASCADE)

    # https://djbook.ru/rel1.9/ref/models/fields.html#default
    # Для полей типа ForeignKey, которые ссылаются на объекты модели, значением по умолчанию должно быть значение поля
    # на которое они ссылаются (pk, если не указан to_field), а не объект модели.
    owner = models.ForeignKey(User, verbose_name='власник', default=get_default_user, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('tysk:main-detail', args=[str(self.pk)])

tysk/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, SetPasswordForm, PasswordChangeForm \
    , PasswordResetForm

from . import models
from django import forms
from django.core import mail
from django.contrib.auth.tokens import default_token_generator
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.contrib.sites.shortcuts import get_current_site


def make_error_not_auth():
    raise forms.ValidationError("Зайдіть в свій профіль, будь ласка.")


class UserForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        del self.fields['password']

    class Meta:
        model = models.User
        fields = ['username', 'first_name', 'last_name', 'email']


class UserSetPasswordForm(SetPasswordForm):
    class Meta:
        model = models.User
        fields = ['password']


class UserChangePasswordForm(PasswordChangeForm):
    class Meta:
        model = models.User
        fields = ['password']


class UserPasswordResetForm(forms.Form):
    template_name = 'tysk/user/user-reset-pass.html'
    email_template_name = 'tysk/user/user-reset-pass-email.html'
    subject_template_name = 'tysk/user/reset_subject.txt'
    from_email = 'noreply@ownsvit.top'
    to_email = ''

    class Meta:
        model = models.User
        fields = ['username', 'email']

    def send_email(self, subject_template_name, email_template_name, context, from_email, to_email,
                   html_email_template_name=None):
        connection = mail.get_connection()
        print('connection', connection)
        if connection.open():
            subject = loader.render_to_string(subject_template_name, context)
            # Email subject *must not* contain newlines
            subject = ''.join(subject.splitlines())
            print('context', context)
            mess = loader.render_to_string(email_template_name, context)
            email1 = mail.EmailMessage(subject, mess, from_email,
                                       [to_email], connection=connection)
            n = email1.send()
            print('n', n)
            connection.close()
        else:
            print('not open(')
            subject = loader.render_to_string(subject_template_name, context)
            # Email subject *must not* contain newlines
            subject = ''.join(subject.splitlines())
            print('context', context)
            mess = loader.render_to_string(email_template_name, context)
            email1 = mail.EmailMessage(subject, mess, from_email,
                                       [to_email], connection=connection)
            n = email1.send()
            print('n', n)

    def save(self, user_object, request):
        print('save')
        username = user_object.username
        print('username', username)
        email = user_object.email
        current_site = get_current_site(request)
        domain = current_site.domain

        context = {'email': email,
                   # 'uname': urlsafe_base64_encode(force_bytes(username)).decode(),
                   'uname': urlsafe_base64_encode(force_bytes(username)),
                   'token': default_token_generator.make_token(user_object),
                   'protocol': 'http',
                   'domain': domain}

        self.send_email(self.subject_template_name, self.email_template_name, context, self.from_email, email)


class TyskUserCreationForm(UserCreationForm):

    class Meta:
        model = models.User
        fields = ['username', 'first_name', 'last_name', 'email', 'groups', 'user_permissions', 'is_staff', 'is_active',
                  'is_superuser']


class RegisterForm(forms.Form):
    GENDER_CHOICES = (
        ('male', 'Чоловіча'),
        ('female', 'Жіноча'),
    )
    TYPE_USER_CHOICES = (
            ('patient', 'Пацієнт'),
            ('doctor', 'Лікар'),
    )
    username = forms.EmailField(label='Електронна пошта')
    password1 = forms.CharField(label='Пароль', help_text='звертайте увагу на мову і регістр', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Підтверження паролю', help_text='', widget=forms.PasswordInput)
    first_name = forms.CharField(label='Ім`я', help_text='ім`я (наприклад - Тарас, Олена)')
    gender = forms.ChoiceField(choices=GENDER_CHOICES, label='Стать', widget=forms.RadioSelect)
    type_user = forms.ChoiceField(choices=TYPE_USER_CHOICES, label='Хто?', widget=forms.RadioSelect)

    def check_passwords_match(self):
        # Check that the two password entries match
        # Визивається в clean
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            # raise forms.ValidationError("Паролі не співпадають")
            return False
        return True

    def clean(self):
        if not self.check_passwords_match():
            super(RegisterForm, self).clean()
            raise forms.ValidationError("Паролі не співпадають")


class IndexForm(forms.Form):
    upper = forms.IntegerField(max_value=300, min_value=0)
    lower = forms.IntegerField(max_value=300, min_value=0)
    pulse = forms.IntegerField(max_value=300, min_value=0)
    email = forms.EmailField()


class ContactForm(forms.Form):
    name = forms.CharField(max_length=50, label='Ім`я:', widget=forms.TextInput(attrs={'class': 'form-control input-lg'
        }), required=False)
    email = forms.EmailField(label='Ваша електронна пошта:', widget=forms.EmailInput(attrs={'class': 'form-control input-lg'}))
    message = forms.CharField(label='', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5',
        'placeholder': 'Повідомлення'}))


class MedicamentCreateForm(forms.ModelForm):
    class Meta:
        model = models.Medicament
        fields = ['name', 'owner']
        widgets = {'owner': forms.HiddenInput}


class MedicamentSuperUserCreateForm(forms.ModelForm):
    class Meta:
        model = models.Medicament
        fields = ['name', 'owner']


class MedicamentUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Medicament
        fields = ['name', 'owner']
        widgets = {'owner': forms.HiddenInput}


class MedicamentSuperUserUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Medicament
        fields = ['name', 'owner']


class PatientCreateForm(forms.ModelForm):
    GENDER_CHOICES = (
        (True, 'Чол'),
        (False, 'Жін '),
    )
    male = forms.ChoiceField(choices=GENDER_CHOICES, label='Стать', widget=forms.RadioSelect())

    class Meta:
        model = models.Patient
        fields = ['doctors', 'male', 'user']
        widgets = {'user': forms.HiddenInput}


class PatientSuperUserCreateForm(PatientCreateForm):
    print('dir(PatientCreateForm)', dir(PatientCreateForm))
    # male = PatientCreateForm.male

    class Meta:
        model = models.Patient
        fields = ['user', 'doctors', 'male']


class PatientUpdateForm(forms.ModelForm):
    GENDER_CHOICES = (
        (True, 'Чол'),
        (False, 'Жін '),
    )
    male = forms.ChoiceField(choices=GENDER_CHOICES, label='Стать', widget=forms.RadioSelect())

    class Meta:
        model = models.Patient
        fields = ['doctors', 'male', 'user']
        widgets = {'user': forms.HiddenInput}


class PatientSuperUserUpdateForm(PatientUpdateForm):

    class Meta:
        model = models.Patient
        fields = ['user', 'doctors', 'male']


class DoctorCreateForm(forms.ModelForm):

    class Meta:
        model = models.Doctor
        fields = ['patients', 'user']
        widgets = {'user': forms.HiddenInput}


class DoctorSuperUserCreateForm(DoctorCreateForm):

    class Meta:
        model = models.Doctor
        fields = ['user', 'patients']


class DoctorUpdateForm(forms.ModelForm):

    class Meta:
        model = models.Doctor
        fields = ['patients', 'user']
        widgets = {'user': forms.HiddenInput}


class DoctorSuperUserUpdateForm(DoctorUpdateForm):

    class Meta:
        model = models.Doctor
        fields = ['user', 'patients']


class PatientChooseMainForm(forms.ModelForm):

    patient = forms.ModelChoiceField(queryset=models.Patient.objects.get_queryset(), label='по пацієнту')

    class Meta:
        model = models.Main
        fields = ['patient']

tysk/templates/tysk/302.html
{% include 'diary/minhead.html' %}
{% load i18n static admin_static%}
{% block content %}
    <h2><a href="/diary/admin/diary/calendar/">{% trans 'The current date is not in the calendar. Enter day of diary' %}
        </a></h2>
    {% block table %} {% endblock table %}
{% endblock content %}

tysk/templates/tysk/add.html
{% extends 'tysk/index.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Тиск - {{ model_title }} - {{ title }}{% endblock %}
{% block header %}
    <!-- Site header -->
    <header class="page-header bg-img size-lg" style="background-image: url({% static 'tysk/img/bg-banner2.jpg' %})"
            xmlns="http://www.w3.org/1999/html">
      <div class="container no-shadow">
        <h1 class="text-center">{{ model_title }}, {{ title|lower }}</h1>
        <p class="lead text-center">{{ object.user.first_name }}</p>
            <style>
               li {
                list-style-type: none; /* Убираем маркеры */
                   text-align: center;
               }
               ul {
                margin-left: 0; /* Отступ слева в браузере IE и Opera */
                padding-left: 0; /* Отступ слева в браузере Firefox, Safari, Chrome */

               }
              </style>
      </div>
    </header>
    <!-- END Site header -->
{% endblock %}
{% block content %}
<main>
    <div class="container login-block">
        {% if user.is_authenticated %}
            <img src="{% static 'tysk/img/logo.jpg' %}" id="click-me" alt="">

            <h5 class="error">
                Неможливо створити ще одного {{ who }} для того ж самого користувача. Ви можете створити нового:
            </h5>

            <a href="{% url 'tysk:register' %}" class="btn btn-success"> Новий користувач </a>

            <h5 class="error">
                чи змінити існуючого.
            </h5>
            <p class="text-center">
            {% if active == 'patient-add' %}
                <a href="{% url 'tysk:patients-list' %}">До списку</a>
            {% else %}
                <a href="{% url 'tysk:doctors-list' %}">До списку</a>
            {% endif %}
             </p>
        {% else %}
            <header class="section-header">
                <span>Ви не ввійшли</span>
            </header>
        {% endif %} {# {% if user.is_authenticated %} #}
    </div>

      <div class="container login-links">
        <p class="text-center"><a href="{% url 'tysk:index' %}">На початкову</a></p>
      </div>
</main>
{% endblock content %}
{% block script %}
    {{ block.super }}
    <script>
        //$(document).ready(function() {
        //var max = 0;
        //$("label").each(function(){
            //if ($(this).width() > max)
                //max = $(this).width();
        //});
        //$("label").width(max);
        //});
    </script>
{% endblock %}
</body>

tysk/templates/tysk/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="Зберігайте історію тиска, пульса та прийому лікарских засобів Вами, Вашими батьками для лікаря">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="{% static 'tysk/img/health.png' %}">
    <link rel="icon" type="image/jpg" href="{% static 'tysk/img/health.png' %}">
    {% block css %}
        <!-- Styles -->
        <link href="{% static 'tysk/css/app.min.css'%}" rel="stylesheet">
    {% endblock css %}
    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,300,400,500,600,800%7COpen+Sans:300,400,500,600,700,800%7CMontserrat:400,700' rel='stylesheet' type='text/css'>
    {% block style %}{% endblock style %}
</head>
{% block body1 %}
<body>
{% endblock body1 %}
    {% block nav_bar %}{% endblock %}
    {% block header %}{% endblock header %}
    {% block content %}{% endblock %}
    {% block footer %}{% endblock %}
    {% block script %}
        <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
        <script>window.jQuery || document.write('<script src="https://code.jquery.com/jquery-1.10.2.min.js"><\/script>')</script>
        <script src="{% static 'tysk/js/app.min.js' %}"></script>
    {% endblock script %}
</body>
</html>

tysk/templates/tysk/confirm-delete.html
{% extends 'tysk/index.html' %}
{% load static %}
{% block title %}Тиск - {{ model_title }} - {{ title }}{% endblock %}
{% block header %}
    <!-- Site header -->
    <header class="page-header bg-img size-lg" style="background-image: url({% static 'tysk/img/bg-banner2.jpg' %})">
      <div class="container no-shadow">
        <h1 class="text-center">{{ model_title }}, {{ title|lower }}</h1>
        <p class="lead text-center">{{ object.name }}</p>
      </div>
    </header>
    <!-- END Site header -->
{% endblock %}
{% block content %}
<main>
    <div class="container login-block">
        <img src="{% static 'tysk/img/logo.jpg' %}" id="click-me" alt="">

        <h5></h5>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <form action="" method="post">{% csrf_token %}
            <p>видалити "{{ object }}"?</p>
            <input class="btn btn-danger" type="submit" value="Згода" />
        </form>
    </div>

  <div class="container login-links">
    <p class="text-center"><a href="{% url 'tysk:index' %}">На початкову</a></p>
  </div>
</main>
{% endblock content %}

tysk/templates/tysk/contact.html
{% extends 'tysk/index.html' %}
{% load static %}
{% block title %}Тиск - Контакти{% endblock %}
{% block header %}
    <!-- Site header -->
    <header class="page-header bg-img size-lg" style="background-image: url({% static 'tysk/img/bg-banner2.jpg' %})">
      <div class="container no-shadow">
        <h1 class="text-center">Зв`жіться з нами</h1>
        <p class="lead text-center">Дзвоніть, пишіть та слідкуйте за нами в соціальних мережах.</p>
      </div>
    </header>
    <!-- END Site header -->
{% endblock %}
{% block content %}
    <!-- Main container -->
    <main>
      <section>
        <div class="container">

          <div id="contact-map" style="height: 500px"></div>

          <br><br>

          <div class="row">
            <div class="col-sm-12 col-md-8">
              <h4>Контактна форма</h4>
              <form action="{% url 'tysk:contact' %}" method="post">
                  {% csrf_token %}
                <div class="form-group">
                    {{ contact_form.name.errors }}
                  <input type="text" class="form-control input-lg" placeholder="Ім`я" name="name" value="{{ name }}">
                </div>

                <div class="form-group">
                    {{ contact_form.email.errors }}
                  <input type="email" class="form-control input-lg" placeholder="Електронна пошта" name="email" value="{{ email }}">
                </div>

                <div class="form-group">
                    {{ contact_form.message.errors }}
                  <textarea class="form-control" rows="5" placeholder="Повідомлення" name="message">{{ message }}</textarea>
                </div>
{#                  {{ contact_form }}#}
                <button type="submit" class="btn btn-primary">Відправити</button>
              </form>
            </div>

            <div class="col-sm-12 col-md-4">
              <h4>Інформація</h4>
              <div class="highlighted-block">
                <dl class="icon-holder">
                  <dt><i class="fa fa-map-marker"></i></dt>
                  <dd> майдан Незалежності, Київ, Україна</dd>

                  <dt><i class="fa fa-phone"></i></dt>
                  <dd>(+380 44) 987 654 3210</dd>

                  <dt><i class="fa fa-fax"></i></dt>
                  <dd>(+380 44) 123 456 7890</dd>

                  <dt><i class="fa fa-envelope"></i></dt>
                  <dd>ownmir@i.ua</dd>
                </dl>
              </div>

              <br>

              <ul class="social-icons size-sm text-center">
                <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
                <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a class="instagram" href="#"><i class="fa fa-instagram"></i></a></li>
              </ul>

            </div>
          </div>

        </div>
      </section>
    </main>
    <!-- END Main container -->
{% endblock content %}
{% block script %}
    {{ block.super }}
    <script src="https://maps.googleapis.com/maps/api/js?callback=initMap" async defer></script>
{% endblock script %}
</body>

tysk/templates/tysk/contact_link.html
<a href="{{ domain }}{% url 'tysk:contact' %}">тут</a>

tysk/templates/tysk/radio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>radio</title>
    <link href="app.min.css" rel="stylesheet">
</head>
<body class="login-page">
<div>
<div class="row">
    <div class="col-sm-12 col-md-6">
        <br>
        <h6><b>Стать</b></h6>
        <span class="radio">
            <input type="radio" name="gender" id="male" value="male" checked>
            <label for="male">Чоловіча</label>
        </span>

        <span class="radio">
            <input type="radio" name="gender" id="female" value="female">
            <label for="female">Жіноча</label>
        </span>
    </div>
    <div class="col-sm-12 col-md-6">
                    <br>
                    <h6><b>Хто?</b></h6>
                    <div class="radio">
                        <input type="radio" name="type-user" id="patient" value="patient" checked>
                        <label for="patient">Пацієнт</label>
                    </div>

                    <div class="radio">
                        <input type="radio" name="type-user" id="doctor" value="doctor">
                        <label for="doctor">Лікар</label>
                    </div>

                </div>
</div>
    </div>
<div>
	<form action="/tysk/user/reg/" method="post">
            <tr><th><label for="id_email">Електронна пошта:</label></th><td>
                <input id="id_email" name="email" type="email" required /></td></tr>
<tr><th><label for="id_password1">Пароль:</label></th><td><input id="id_password1" name="password1" type="password" required /><br /><span class="helptext">звертайте увагу на мову і регістр</span></td></tr>
<tr><th><label for="id_password2">Підтверження паролю:</label></th><td><input id="id_password2" name="password2" type="password" required /></td></tr>
<tr><th><label for="id_first_name">Ім`я:</label></th><td><input id="id_first_name" name="first_name" type="text" required /><br /><span class="helptext">ім`я (наприклад - Тарас, Олена)</span></td></tr>
<tr><th><label for="id_gender_0">Стать:</label></th><td><ul id="id_gender"><li><label for="id_gender_0"><input id="id_gender_0" name="gender" type="radio" value="male" required /> Чоловіча</label></li>
<li><label for="id_gender_1"><input id="id_gender_1" name="gender" type="radio" value="female" required /> Жіноча</label></li></ul></td></tr>
<tr><th><label for="id_type_user_0">Хто?</label></th><td><ul id="id_type_user"><li><label for="id_type_user_0"><input id="id_type_user_0" name="type_user" type="radio" value="patient" required /> Пацієнт</label></li>
<li><label for="id_type_user_1"><input id="id_type_user_1" name="type_user" type="radio" value="doctor" required /> Лікар</label></li></ul></td></tr>
            <button class="btn btn-primary btn-block" type="submit">Регістрація</button>
</div>
</body>
</html>