itysk/urls.py
from django.conf.urls import url, include
from django.contrib import admin as tysk_admin

urlpatterns = [
    url(r'^tysk/admin/', tysk_admin.site.urls),
    # https://stackoverflow.com/questions/48608894/specifying-a-namespace-in-include-without-providing-an-app-name
    # url(r'^tysk/', include('tysk.urls', namespace="tysk")),
    url(r'^tysk/', include(('tysk.urls', 'tysk'), namespace="tysk")),
    url(r'^tysk/accounts/', include('allauth.urls')),
]

tysk/urls.py
from django.conf.urls import url
from tysk import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^doctors/$', views.DoctorsList.as_view(), name='doctors-list'),
    url(r'^doctors/(?P<pk>[0-9]+)/$', views.DoctorDetail.as_view(), name='doctor-detail'),
    url(r'^doctors/add/$', views.doctor_add, name='doctor-add'),
    url(r'^doctors/(?P<pk>[0-9]+)/update/$', views.DoctorUpdate.as_view(), name='doctor-update'),
    url(r'^doctors/(?P<pk>[0-9]+)/confirm/$', views.DoctorDelete.as_view(), name='doctor-delete'),
    url(r'^mains/$', views.MainsList.as_view(), name='mains-list'),
    url(r'^mainsget/$', views.main_filter, name='main-filter'),
    url(r'^mains/(?P<pk>[0-9]+)/$', views.MainDetail.as_view(), name='main-detail'),
    url(r'^mains/add/$', views.MainCreate.as_view(), name='main-add'),
    url(r'^mains/(?P<pk>[0-9]+)/update/$', views.MainUpdate.as_view(), name='main-update'),
    url(r'^mains/(?P<pk>[0-9]+)/confirm/$', views.MainDelete.as_view(), name='main-delete'),
    url(r'^medicaments/$', views.MedicamentsList.as_view(), name='medicaments-list'),
    url(r'^medicaments/(?P<pk>[0-9]+)/$', views.MedicamentDetail.as_view(), name='medicament-detail'),
    url(r'^medicaments/add/$', views.MedicamentCreate.as_view(), name='medicament-add'),
    url(r'^medicaments/(?P<pk>[0-9]+)/update/$', views.MedicamentUpdate.as_view(), name='medicament-update'),
    url(r'^medicaments/(?P<pk>[0-9]+)/confirm/$', views.MedicamentDelete.as_view(), name='medicament-delete'),
    url(r'^users/login/$', views.login, name='login'),
    url(r'^users/reg/$', views.register, name='register'),
    url(r'^users/forget/$', views.forget_password, name='forget-password'),
    url(r'^users/$', views.UsersList.as_view(), name='users-list'),
    # url(r'^users/create/$', views.UserCreate.as_view(), name='user-create'),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='user-detail'),
    url(r'^users/(?P<pk>[0-9]+)/update/$', views.UserUpdate.as_view(), name='user-update'),
    url(r'^users/(?P<pk>[0-9]+)/confirm/$', views.UserDelete.as_view(), name='user-delete'),
    url(r'^users/(?P<pk>[0-9]+)/change/pass/$', views.UserChangePass.as_view(), name='user-change-password'),
    url(r'^users/(?P<pk>[0-9]+)/change/pass_old/$', views.UserChangePassOld.as_view(), name='user-change-pass-old'),
    url(r'^users/(?P<username>.*)/reset/pass/$', views.UserResetPass.as_view(), name='user-reset-password'),
    url(r'^users/reset/done/', views.UserPassResetDoneView.as_view(), name='user-reset-password-done'),
    url(r'^users/reset/(?P<unameb64>.*)/(?P<token>.*)/', views.UserPasswordResetConfirmView.as_view(), name='user-reset-password-confirm'),
    url(r'^users/reset/complete/', views.PasswordResetCompleteView.as_view(), name='user-reset-password-complete'),
    url(r'^users/logout/$', views.logout, name='logout'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^patients/$', views.PatientsList.as_view(), name='patients-list'),
    url(r'^patients/(?P<pk>[0-9]+)/$', views.PatientDetail.as_view(), name='patient-detail'),
    url(r'^patients/add/$', views.patient_add, name='patient-add'),
    url(r'^patients/(?P<pk>[0-9]+)/update/$', views.PatientUpdate.as_view(), name='patient-update'),
    url(r'^patients/(?P<pk>[0-9]+)/confirm/$', views.PatientDelete.as_view(), name='patient-delete'),
    url(r'^code/$', views.code, name='code')
]

tysk/views.py
from django.contrib.auth import authenticate, login as auth_login, \
    logout as auth_logout  # http://stackoverflow.com/questions/39316948/
from django.contrib.auth.models import User, Group
from django.core.exceptions import ObjectDoesNotExist
from django.utils.datastructures import MultiValueDictKeyError
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
# typeerror-login-takes-1-positional-argument-but-2-were-given
from django.utils.timezone import now, localtime
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse
from itysk import settings
from decouple import config

from . import forms
from . import models
from .utilities import which_invoked
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.http import is_safe_url, urlsafe_base64_decode
from django.core.exceptions import ValidationError
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.template.loader import render_to_string
from django.contrib.sites.models import Site
from django.db.models import Q
import json
from el_pagination.views import AjaxListView
from django.views.generic.list import MultipleObjectMixin, TemplateResponseMixin, View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def auth_or_create(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                # Redirect to a success page.
            else:
                # Return a 'disabled account' error message
                pass
        else:
            # Return an 'invalid login' error message.
            pass
    if not request.user.is_authenticated:
        create_user_self(request)
    return context


def index(request):
    # початкова
    context = {'active': 'index'}
    number_of_users = [ number_of_users for number_of_users in range(919, 1149)]
    context['number_of_users'] = number_of_users
    user = request.user
    if not request.user.is_authenticated:
        create_user_self(request)
        print("create_user_self виконано!")
    if request.method == 'POST':
        main_form = forms.IndexForm(request.POST)
        upper = request.POST['upper']
        lower = request.POST['lower']
        pulse = request.POST['pulse']
        email = request.POST['email']
        context['main_form'] = main_form
        if not request.user.is_authenticated and 'database_save' in main_form.data:
            forms.make_error_not_auth()  # додаємо помилку
        if main_form.is_valid():
            if 'send_email' in main_form.data:
                print('send_email !')
                from django.core import mail
                connection = mail.get_connection()
                if connection.open():
                    there = '\n Поскаржитись на цей лист можна тут www.ownsvit.top/tysk/contact/ '
                        # {'protocol': 'https://', 'domain': Site.objects.get_current(request).domain})
                    subject = 'Тиск. www.ownsvit.top/tysk/. Дата: ' + str(localtime().date()) + ', час ' + str(localtime().time())
                    mess = 'Вітаю! \nЦей лист прийшов Вам з сайту www.ownsvit.top/tysk/ . Верхній тиск: ' + str(upper) + \
                        ', нижній ' + str(lower) + ', пульс ' + str(pulse) + '.\n З повагою, команда Тиск.'
                    email1 = mail.EmailMessage(subject, mess + there, 'postmaster@ownsvit.top',
                                               [email], connection=connection)
                    # email1.attach_alternative(mess + there, 'text/html')
                    email1.send()
                    connection.close()
                    print(':-)')
                return render(request, 'tysk/index.html', context)
            # Створюємо main
            main = models.Main()
            # Шукаємо паціента
            try:
                patient = models.Patient.objects.get(user=user)
            except ObjectDoesNotExist:
                patient = models.Patient()
                patient.user = user
                patient.male = True
                patient.save()
                self_user = User.objects.get(username=config('self'))
                try:
                    self_doctor = models.Doctor.objects.get(user=self_user)
                except ObjectDoesNotExist:
                    self_doctor = models.Doctor()
                    self_doctor.user = self_user
                    self_doctor.save()
                    test_user = User.objects.get(username=config('test'))
                    try:
                        test_patient = models.Patient.objects.get(user=test_user)
                    except ObjectDoesNotExist:
                        test_patient = models.Patient()
                        test_patient.user = test_user
                        test_patient.male = True
                        test_patient.save()
                        print('*** test user created in views/index()! ***')
                        test_patient.doctors.add(self_doctor)
                patient.doctors.add(self_doctor)
            main.patient = patient
            # Шукаємо доктора
            if not patient.doctors.exists():
                self_user = User.objects.get(username=config('self'))
                self_doctor = models.Doctor.objects.get(user=self_user)
                patient.doctors.add(self_doctor)
            doctor = patient.doctors.all()[0]
            main.doctor = doctor
            main.upper = main_form.cleaned_data.get('upper')
            main.lower = main_form.cleaned_data.get('lower')
            main.pulse = main_form.cleaned_data.get('pulse')
            # main.date default - current
            # main.time default - current
            # Шукаємо ліки
            try:
                medicament = models.Medicament.objects.get(name='Не приймали')
            except ObjectDoesNotExist:
                medicament = models.Medicament()
                medicament.name = 'Не приймали'
                medicament.save()
                print('Ліки створено!')
            main.medicament = medicament
            main.owner = user
            main.save()
            # return HttpResponse('First go...')
            return redirect(main)
        else:
            main_form = forms.IndexForm(request.POST)
            print(request.POST)
            context['main_form'] = main_form
            context['upper'] = upper
            context['lower'] = lower
            context['pulse'] = pulse
            context['email'] = email
        return render(request, 'tysk/index.html', context)
    else:
        if user.is_authenticated:
            main_form = forms.IndexForm(initial={'email': user.email, 'pulse': '60'})
            if user.is_superuser:
                context['is_superuser'] = 'is_superuser'
                main_list = models.Main.objects.order_by('-date', '-time')[:5]
            else:
                main_list = models.Main.objects.filter(owner=user)
                """
                try:
                    # чи пацієнт
                    current_patient = models.Patient.objects.get(user=request.user)
                    main_list = models.Main.objects.filter(patient=current_patient).order_by('-date', '-time')[:5]
                except ObjectDoesNotExist:
                    # чи доктор
                    current_doctor = models.Doctor.objects.get(user=request.user)
                    main_list = models.Main.objects.filter(doctor=current_doctor).order_by('-date', '-time')[:5]
                """
        else:
            main_form = forms.IndexForm(initial={'pulse': '60'})
            main_list = []
        context['main_form'] = main_form
        context['main_list'] = main_list
        return render(request, 'tysk/index.html', context)


def create_user_self(request):
    # створення користувача "Суперюзер" при впровадженні
    try:
        user = User.objects.get(username=config('suser'))
    except ObjectDoesNotExist:
        # Немає
        user = User.objects.create_superuser(config('suser'), config('suser_email'), config('suser_pass'))
        user.first_name = 'В'
        user.last_name = 'Суперюзер'
        user.middle_name = 'В'
        user.groups.set(Group.objects.all())
        user.save()
    # створення користувача "Я сам лікар)" при впровадженні
    try:
        user = User.objects.get(username=config('self'))
    except ObjectDoesNotExist:
        # Немає
        user = User.objects.create_user(config('self'), config('self_email'), config('self_pass'))
        user.first_name = 'В'
        user.last_name = 'Я сам лікар)'
        user.middle_name = 'В'
        user.is_superuser = False
        user.is_staff = True
        user.groups.set(Group.objects.all())
        user.save()
    # створення користувача "Тест паціент" при впровадженні
    try:
        user = User.objects.get(username=config('test'))
    except ObjectDoesNotExist:
        # Немає
        user = User.objects.create_user(config('test'), config('test_email'), config('test_pass'))
        user.first_name = 'В'
        user.last_name = 'Тест паціент'
        user.middle_name = 'В'
        user.is_superuser = False
        user.is_staff = True
        user.groups.set(Group.objects.all())
        user.save()
        print('*** test user created in views/create_user_self()! ***')
    try:

tysk/templates/tysk/user/doctor-created.html
{% extends 'tysk/index.html' %}
{% load static %}
{% block title %}Тиск - Доктора створено.{% endblock %}
{% block header %}
    <!-- Site header -->
    <header class="page-header bg-img size-lg" style="background-image: url({% static 'tysk/img/bg-banner2.jpg' %})">
      <div class="container no-shadow">
        <h1 class="text-center">Поздоровляємо!</h1>
        <p class="lead text-center">Доктора створено!</p>
      </div>
    </header>
    <!-- END Site header -->
{% endblock %}
{% block content %}
    <!-- Main container -->
    <main>
      <!-- User exists -->
      <section>
          <img src="{% static 'tysk/img/logo.jpg' %}" id="click-me" alt="">
          <p></p>
      </section>
      <!-- END User exists -->
      <div class="login-links">
          {#<a class="pull-left" href="{% url 'tysk:forget-password' %}">Забули пароль?</a>#}
          <p class="text-left"><a class="txt-brand" href="{% url 'tysk:register' %}">Регістрація</a></p>
          <p class="text-left"><a class="txt-brand" href="{% url 'tysk:index' %}">На початкову</a>
      </div>
    </main>
    <!-- END Main container -->
{% endblock content %}
</body>

tysk/templates/tysk/user/user-change-pass.html
{% extends 'tysk/user/user-login.html' %}
{% load static%}
{% block title %}Тиск - Зміна пароля{% endblock %}
{% block content %}
<main>
    <div class="login-block">
        <img src="{% static 'tysk/img/logo.jpg' %}" id="click-me" alt="">
        <h1>Зміна пароля</h1>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <form action="" method="post">{% csrf_token %}
            <p>Змінити пароль користувачу <strong>{{ user.username }}</strong>?</p>
            {{ form_user.as_p }}
            <input type="submit" value="Зберегти" />
        </form>
    </div>

      <div class="login-links">
        <p class="text-center"><a href="{% url 'tysk:login' %}">Вхід</a></p>
      </div>
</main>
{% endblock content %}
{% block script %}
    {{ block.super }}
{% endblock %}
</body>

tysk/templates/tysk/user/user-create.html
{% extends 'tysk/static_add.html' %}
{% load static%}
{% block title %}Тиск - Створення користувача{% endblock %}
{% block css %}
    {{ block.super }}

{% endblock css %}
{% block body1 %}
<body class="login-page">
{% endblock body1 %}
{% block content %}
    <main>

      <div class="login-block">
        <img src="{% static 'tysk/img/logo.jpg' %}" id="click-me" alt="" style="{opacity: 1;}">

        <h1>Створення користувача</h1>

          {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <form action="" method="post">{% csrf_token %}
            {{ form_user.as_p }}
            <input type="submit" value="Створити" />
        </form>
        </div>

          <div class="login-links">
            <p class="text-center"><a href="{% url 'tysk:index' %}">На головну</a></p>
          </div>
    </main>
{% endblock content %}
{% block script %}
    {{ block.super }}
{% endblock %}
</body>

tysk/templates/tysk/user/user-detail.html
{% extends 'tysk/user/user-login.html' %}
{% load static%}
{% block title %}Тиск - Користувач{% endblock %}
{% block content %}
<main>
    <div class="login-block">
        <img src="{% static 'tysk/img/logo.jpg' %}" id="click-me" alt="">

        <h1>last_name - {{ user.last_name }} ({{ user.username }})</h1>
        <ul>
            <li>username - {{ user.username }}</li>
            <li>first_name - {{ user.first_name }}</li>
            <li>last_name - {{ user.last_name }}</li>
            <li>email - {{ user.email }}</li>
            <li>is_staff - {{ user.is_staff }}</li>
            <li>is_active - {{ user.is_active }}</li>
            <li>is_superuser - {{ user.is_superuser }}</li>
            <li>last_login - {{ user.last_login }}</li>
            <li>date_joined - {{ user.date_joined }}</li>
        </ul>
    </div>

      <div class="login-links">
        <p class="text-center"><a href="{% url 'tysk:index' %}">На головну</a></p>
      </div>
</main>
{% endblock content %}
{% block script %}
    {{ block.super }}
{% endblock %}
</body>

tysk/templates/tysk/user/user-exists.html
{% extends 'tysk/index.html' %}
{% load static %}
{% block title %}Тиск - Користувач вже існує.{% endblock %}
{% block header %}
    <!-- Site header -->
    <header class="page-header bg-img size-lg" style="background-image: url({% static 'tysk/img/bg-banner2.jpg' %})">
      <div class="container no-shadow">
        <h1 class="text-center">Помилка(</h1>
        <p class="lead text-center">Такий користувач вже існує!</p>
      </div>
    </header>
    <!-- END Site header -->
{% endblock %}
{% block content %}
    <!-- Main container -->
    <main>
      <!-- User exists -->
      <section>
          <img src="{% static 'tysk/img/sad.jpg' %}" id="click-me" alt="">
          <p></p>
      </section>
      <!-- END User exists -->
      <div class="login-links">
{#          <a class="pull-left" href="{% url 'tysk:forget-password' %}">Забули пароль?</a>#}
          <p class="text-left"><a class="txt-brand" href="{% url 'tysk:register' %}">Регістрація</a></p>
          <p class="text-left"><a class="txt-brand" href="{% url 'tysk:index' %}">На початкову</a>
          </p>
      </div>
    </main>
    <!-- END Main container -->
{% endblock content %}
</body>

tysk/templates/tysk/user/user-forget-pass.html
{% extends 'tysk/user/user-login.html' %}
{% load static%}
{% block title %}Тиск - Запит{% endblock %}
{% block content %}
<main>
    <div class="login-block">
        <img src="{% static 'tysk/img/logo.jpg' %}" id="click-me" alt="">
        <h1>Запит на скидання пароля</h1>

        <form action="#">

          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon"><i class="ti-email"></i></span>
              <input type="text" class="form-control" placeholder="Електронна пошта">
            </div>
          </div>

          <p>
            <a href="mailto:ownsvit@ukr.net?subject=Скинути {{ user.username }} на пошту {{ user.email }}">
                Запрос з Вашої поштової програми за замовчуванням
            </a>
          </p>
        </form>
      </div>

      <div class="login-links">
        <p class="text-center"><a href="{% url 'tysk:login' %}">Назад до входу</a></p>
        <a href="{% url 'tysk:index' %}"> На початкову</a>
      </div>
</main>
{% endblock content %}
{% block script %}
    {{ block.super }}
{% endblock %}
</body>

tysk/templates/tysk/user/user-login.html
{% extends 'tysk/static_add.html' %}
{% load static%}
{% load socialaccount %}
{% providers_media_js %}
{% block title %}Тиск - Ввійдіть{% endblock %}
{% block css %}
    {{ block.super }}

{% endblock css %}
{% block body1 %}
<body class="login-page">
{% endblock body1 %}
{% block content %}
    <main>

      <div class="login-block">
        <img src="{% static 'tysk/img/logo.jpg' %}" id="click-me" alt="" style="{opacity: 1;}">

        <h1>Ввійдіть в свій кабінет</h1>

          {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <form action="{% url 'tysk:login' %}?next={% url 'tysk:index' %}" method="post">
        {% csrf_token %}
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon"><i class="ti-email"></i></span>
              <input name="username" type="text" class="form-control" placeholder="Електронна пошта">
            </div>
          </div>

          <hr class="hr-xs">

          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon"><i class="ti-unlock"></i></span>
              <input name="password" type="password" class="form-control" placeholder="Пароль">
            </div>
          </div>

          <button class="btn btn-primary btn-block" type="submit">Вхід</button>

          <div class="login-footer">
            <h6>Чи ввійдіть через</h6>
            <ul class="social-icons">
              <li><a class="facebook" href="{% provider_login_url "facebook" method="oauth2" %}"><i class="fa fa-facebook"></i></a></li>
              <li><a class="google-plus" href="{% provider_login_url "google" method="oauth2" %}"><i class="fa fa-google"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>

        </form>
      </div>

      <div class="login-links">
          <a class="pull-left" href="{% url 'tysk:forget-password' %}">Забули пароль?</a>
          <a class="pull-right" href="{% url 'tysk:register' %}">Регістрація</a>
          <p class="text-center"><a class="txt-brand" href="{% url 'tysk:index' %}">На головну</a>
          </p>
      </div>


    </main>
{% endblock content %}
{% block script %}
    {{ block.super }}
    <script>
            <!--
            $( "#click-me" ).click(function() {
              $( "#click-me" ).animate({
                opacity: 0,
              }, 2000, function() {
                // Animation complete. https://jquery-docs.ru/animate/
              });
            });
            // -->
    </script>
{% endblock %}
</body>

tysk/templates/tysk/user/user-reset-pass-complete.html
{% extends 'tysk/user/user-login.html' %}
{% load i18n static%}
{% block title %}Тиск - Завершення{% endblock %}
{% block content %}
<main>
    <div class="login-block">
        <img src="{% static 'tysk/img/logo.jpg' %}" id="click-me" alt="">
        <h1>Завершено</h1>
        <p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

        <p><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>

    </div>

    <div class="login-links">
        <p class="text-center"><a href="{% url 'tysk:index' %}">На головну</a></p>
    </div>
</main>
{% endblock content %}
{% block script %}
    {{ block.super }}
{% endblock %}
</body>

tysk/templates/tysk/user/user-reset-pass-confirm.html
{% extends 'tysk/user/user-login.html' %}
{% load i18n static%}
{% block title %}Тиск - Підтвердження{% endblock %}
{% block content %}
<main>
    <div class="login-block">
        <img src="{% static 'tysk/img/logo.jpg' %}" id="click-me" alt="">
        <h1>Підтвердження відправлення</h1>
        {% if validlink %}

            <p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

            <form method="post">{% csrf_token %}
            <fieldset class="module aligned">
                <div class="form-row field-password1">
                    {{ form.new_password1.errors }}
                    <label for="id_new_password1">{% trans 'New password:' %}</label>
                    {{ form.new_password1 }}
                </div>
                <div class="form-row field-password2">
                    {{ form.new_password2.errors }}
                    <label for="id_new_password2">{% trans 'Confirm password:' %}</label>
                    {{ form.new_password2 }}
                </div>
                <input type="submit" value="{% trans 'Change my password' %}">
            </fieldset>
            </form>

        {% else %}

            <p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>
        {% endif %}
{#        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}#}
{#        <form action="" method="post">{% csrf_token %}#}
{#            <p>відправити "{{ object }}"?</p>#}
{#            <input type="submit" value="Згода" />#}
{#        </form>#}
    </div>

      <div class="login-links">
        <p class="text-center"><a href="{% url 'tysk:index' %}">На головну</a></p>
      </div>
</main>
{% endblock content %}
{% block script %}
    {{ block.super }}
{% endblock %}
</body>

tysk/templates/tysk/user/user-reset-pass-done.html
{% extends 'tysk/user/user-login.html' %}
{% load i18n static%}
{% block title %}Тиск - Email відправлено {{ title }}{% endblock %}
{% block content %}
<main>
    <div class="login-block">
        <img src="{% static 'tysk/img/logo.jpg' %}" id="click-me" alt="">
        <h1>Email відправлено</h1>
        <p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>

        <p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>
    </div>
    <div class="login-links">
        <a href="{% url 'tysk:index' %}"> На початкову</a>
    </div>
</main>
{% endblock content %}
{% block script %}
    {{ block.super }}
{% endblock %}
</body>

tysk/templates/tysk/user/user-reset-pass-email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>user reset password email</title>
</head>
<body>
    {% autoescape off %}
    Для того, щоб ініціювати процес скидання пароля для ваc {{ username }},
    перейдіть:
b64: {{ uname }} token: {{ token }}
    {{ protocol }}://{{ domain }}:8000{% url 'tysk:user-reset-password-confirm' unameb64=uname token=token %}

    Якщо посилання вище не працює, будь ласка, скопіюйте та вставте URL в новому вікні браузера замість цього.

    З повагою,
    команда Тиск
    {% endautoescape %}
</body>
</html>

tysk/templates/tysk/user/user-reset-pass.html
{% extends 'tysk/user/user-login.html' %}
{% load static%}
{% block title %}Тиск - Запит {{ title }}{% endblock %}
{% block content %}
<main>
    <div class="login-block">
        <img src="{% static 'tysk/img/logo.jpg' %}" id="click-me" alt="">
        <h1>Запит на скидання пароля</h1>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <form action="#" method="post">{% csrf_token %}
            {% if form_user.email.errors %}
                {{ form_user.email.errors }}
            {% endif %}
            <div>
                Скинути пароль користувачу
                <input type="text" class="form-control" placeholder="Користувач" name="username" value="{{ user.username }}">
                на пошту
                <input type="email" class="form-control" placeholder="email" name="email" value="{{ user.email }}">?
            </div>
            <br>
            <input type="submit" value="Підтвердити" />
        </form>
    </div>
    <div class="login-links">
{#        <a href="mailto:noreply@ownsvit.top?subject=Скинути {{ form_user.username }} на пошту {{ form_user.email }}">#}
        <p>
            <a href="mailto:ownsvit@ukr.net?subject=Скинути {{ user.username }} на пошту {{ user.email }}">
                Запрос з Вашої поштової програми за замовчуванням
            </a>
        </p>
        <a href="{% url 'tysk:index' %}"> На початкову</a>
    </div>
</main>
{% endblock content %}
{% block script %}
    {{ block.super }}
{% endblock %}
</body>